//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFACliente_asmx.ServiceGestoresWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Gestores", Namespace="http://schemas.datacontract.org/2004/07/ServiciosWeb.ServicioWFC2.Models")]
    [System.SerializableAttribute()]
    public partial class Gestores : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int lanzamientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string desarrolladorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int lanzamiento {
            get {
                return this.lanzamientoField;
            }
            set {
                if ((this.lanzamientoField.Equals(value) != true)) {
                    this.lanzamientoField = value;
                    this.RaisePropertyChanged("lanzamiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string desarrollador {
            get {
                return this.desarrolladorField;
            }
            set {
                if ((object.ReferenceEquals(this.desarrolladorField, value) != true)) {
                    this.desarrolladorField = value;
                    this.RaisePropertyChanged("desarrollador");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceGestoresWCF.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetGestor", ReplyAction="http://tempuri.org/IService1/GetGestorResponse")]
        WFACliente_asmx.ServiceGestoresWCF.Gestores GetGestor(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetGestor", ReplyAction="http://tempuri.org/IService1/GetGestorResponse")]
        System.Threading.Tasks.Task<WFACliente_asmx.ServiceGestoresWCF.Gestores> GetGestorAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetGestores", ReplyAction="http://tempuri.org/IService1/GetGestoresResponse")]
        System.Collections.Generic.List<WFACliente_asmx.ServiceGestoresWCF.Gestores> GetGestores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetGestores", ReplyAction="http://tempuri.org/IService1/GetGestoresResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WFACliente_asmx.ServiceGestoresWCF.Gestores>> GetGestoresAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WFACliente_asmx.ServiceGestoresWCF.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WFACliente_asmx.ServiceGestoresWCF.IService1>, WFACliente_asmx.ServiceGestoresWCF.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WFACliente_asmx.ServiceGestoresWCF.Gestores GetGestor(int id) {
            return base.Channel.GetGestor(id);
        }
        
        public System.Threading.Tasks.Task<WFACliente_asmx.ServiceGestoresWCF.Gestores> GetGestorAsync(int id) {
            return base.Channel.GetGestorAsync(id);
        }
        
        public System.Collections.Generic.List<WFACliente_asmx.ServiceGestoresWCF.Gestores> GetGestores() {
            return base.Channel.GetGestores();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WFACliente_asmx.ServiceGestoresWCF.Gestores>> GetGestoresAsync() {
            return base.Channel.GetGestoresAsync();
        }
    }
}
