//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFACliente_asmx.ServiceGestoresASMX {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfGestores_Bd", Namespace="http://tempuri.org/", ItemName="gestores_Bd")]
    [System.SerializableAttribute()]
    public class ArrayOfGestores_Bd : System.Collections.Generic.List<WFACliente_asmx.ServiceGestoresASMX.gestores_Bd> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="gestores_Bd", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class gestores_Bd : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        private System.Nullable<int> lanzamientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string desarrolladorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<int> lanzamiento {
            get {
                return this.lanzamientoField;
            }
            set {
                if ((this.lanzamientoField.Equals(value) != true)) {
                    this.lanzamientoField = value;
                    this.RaisePropertyChanged("lanzamiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string desarrollador {
            get {
                return this.desarrolladorField;
            }
            set {
                if ((object.ReferenceEquals(this.desarrolladorField, value) != true)) {
                    this.desarrolladorField = value;
                    this.RaisePropertyChanged("desarrollador");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceGestoresASMX.GestoresServiceSoap")]
    public interface GestoresServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetAllGestoresResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllGestores", ReplyAction="*")]
        WFACliente_asmx.ServiceGestoresASMX.GetAllGestoresResponse GetAllGestores(WFACliente_asmx.ServiceGestoresASMX.GetAllGestoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllGestores", ReplyAction="*")]
        System.Threading.Tasks.Task<WFACliente_asmx.ServiceGestoresASMX.GetAllGestoresResponse> GetAllGestoresAsync(WFACliente_asmx.ServiceGestoresASMX.GetAllGestoresRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetGestorResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGestor", ReplyAction="*")]
        WFACliente_asmx.ServiceGestoresASMX.GetGestorResponse GetGestor(WFACliente_asmx.ServiceGestoresASMX.GetGestorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGestor", ReplyAction="*")]
        System.Threading.Tasks.Task<WFACliente_asmx.ServiceGestoresASMX.GetGestorResponse> GetGestorAsync(WFACliente_asmx.ServiceGestoresASMX.GetGestorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllGestoresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllGestores", Namespace="http://tempuri.org/", Order=0)]
        public WFACliente_asmx.ServiceGestoresASMX.GetAllGestoresRequestBody Body;
        
        public GetAllGestoresRequest() {
        }
        
        public GetAllGestoresRequest(WFACliente_asmx.ServiceGestoresASMX.GetAllGestoresRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllGestoresRequestBody {
        
        public GetAllGestoresRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllGestoresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllGestoresResponse", Namespace="http://tempuri.org/", Order=0)]
        public WFACliente_asmx.ServiceGestoresASMX.GetAllGestoresResponseBody Body;
        
        public GetAllGestoresResponse() {
        }
        
        public GetAllGestoresResponse(WFACliente_asmx.ServiceGestoresASMX.GetAllGestoresResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllGestoresResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WFACliente_asmx.ServiceGestoresASMX.ArrayOfGestores_Bd GetAllGestoresResult;
        
        public GetAllGestoresResponseBody() {
        }
        
        public GetAllGestoresResponseBody(WFACliente_asmx.ServiceGestoresASMX.ArrayOfGestores_Bd GetAllGestoresResult) {
            this.GetAllGestoresResult = GetAllGestoresResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGestorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGestor", Namespace="http://tempuri.org/", Order=0)]
        public WFACliente_asmx.ServiceGestoresASMX.GetGestorRequestBody Body;
        
        public GetGestorRequest() {
        }
        
        public GetGestorRequest(WFACliente_asmx.ServiceGestoresASMX.GetGestorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGestorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetGestorRequestBody() {
        }
        
        public GetGestorRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGestorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGestorResponse", Namespace="http://tempuri.org/", Order=0)]
        public WFACliente_asmx.ServiceGestoresASMX.GetGestorResponseBody Body;
        
        public GetGestorResponse() {
        }
        
        public GetGestorResponse(WFACliente_asmx.ServiceGestoresASMX.GetGestorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGestorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WFACliente_asmx.ServiceGestoresASMX.gestores_Bd GetGestorResult;
        
        public GetGestorResponseBody() {
        }
        
        public GetGestorResponseBody(WFACliente_asmx.ServiceGestoresASMX.gestores_Bd GetGestorResult) {
            this.GetGestorResult = GetGestorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GestoresServiceSoapChannel : WFACliente_asmx.ServiceGestoresASMX.GestoresServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestoresServiceSoapClient : System.ServiceModel.ClientBase<WFACliente_asmx.ServiceGestoresASMX.GestoresServiceSoap>, WFACliente_asmx.ServiceGestoresASMX.GestoresServiceSoap {
        
        public GestoresServiceSoapClient() {
        }
        
        public GestoresServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestoresServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestoresServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestoresServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WFACliente_asmx.ServiceGestoresASMX.GetAllGestoresResponse WFACliente_asmx.ServiceGestoresASMX.GestoresServiceSoap.GetAllGestores(WFACliente_asmx.ServiceGestoresASMX.GetAllGestoresRequest request) {
            return base.Channel.GetAllGestores(request);
        }
        
        public WFACliente_asmx.ServiceGestoresASMX.ArrayOfGestores_Bd GetAllGestores() {
            WFACliente_asmx.ServiceGestoresASMX.GetAllGestoresRequest inValue = new WFACliente_asmx.ServiceGestoresASMX.GetAllGestoresRequest();
            inValue.Body = new WFACliente_asmx.ServiceGestoresASMX.GetAllGestoresRequestBody();
            WFACliente_asmx.ServiceGestoresASMX.GetAllGestoresResponse retVal = ((WFACliente_asmx.ServiceGestoresASMX.GestoresServiceSoap)(this)).GetAllGestores(inValue);
            return retVal.Body.GetAllGestoresResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WFACliente_asmx.ServiceGestoresASMX.GetAllGestoresResponse> WFACliente_asmx.ServiceGestoresASMX.GestoresServiceSoap.GetAllGestoresAsync(WFACliente_asmx.ServiceGestoresASMX.GetAllGestoresRequest request) {
            return base.Channel.GetAllGestoresAsync(request);
        }
        
        public System.Threading.Tasks.Task<WFACliente_asmx.ServiceGestoresASMX.GetAllGestoresResponse> GetAllGestoresAsync() {
            WFACliente_asmx.ServiceGestoresASMX.GetAllGestoresRequest inValue = new WFACliente_asmx.ServiceGestoresASMX.GetAllGestoresRequest();
            inValue.Body = new WFACliente_asmx.ServiceGestoresASMX.GetAllGestoresRequestBody();
            return ((WFACliente_asmx.ServiceGestoresASMX.GestoresServiceSoap)(this)).GetAllGestoresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WFACliente_asmx.ServiceGestoresASMX.GetGestorResponse WFACliente_asmx.ServiceGestoresASMX.GestoresServiceSoap.GetGestor(WFACliente_asmx.ServiceGestoresASMX.GetGestorRequest request) {
            return base.Channel.GetGestor(request);
        }
        
        public WFACliente_asmx.ServiceGestoresASMX.gestores_Bd GetGestor(int id) {
            WFACliente_asmx.ServiceGestoresASMX.GetGestorRequest inValue = new WFACliente_asmx.ServiceGestoresASMX.GetGestorRequest();
            inValue.Body = new WFACliente_asmx.ServiceGestoresASMX.GetGestorRequestBody();
            inValue.Body.id = id;
            WFACliente_asmx.ServiceGestoresASMX.GetGestorResponse retVal = ((WFACliente_asmx.ServiceGestoresASMX.GestoresServiceSoap)(this)).GetGestor(inValue);
            return retVal.Body.GetGestorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WFACliente_asmx.ServiceGestoresASMX.GetGestorResponse> WFACliente_asmx.ServiceGestoresASMX.GestoresServiceSoap.GetGestorAsync(WFACliente_asmx.ServiceGestoresASMX.GetGestorRequest request) {
            return base.Channel.GetGestorAsync(request);
        }
        
        public System.Threading.Tasks.Task<WFACliente_asmx.ServiceGestoresASMX.GetGestorResponse> GetGestorAsync(int id) {
            WFACliente_asmx.ServiceGestoresASMX.GetGestorRequest inValue = new WFACliente_asmx.ServiceGestoresASMX.GetGestorRequest();
            inValue.Body = new WFACliente_asmx.ServiceGestoresASMX.GetGestorRequestBody();
            inValue.Body.id = id;
            return ((WFACliente_asmx.ServiceGestoresASMX.GestoresServiceSoap)(this)).GetGestorAsync(inValue);
        }
    }
}
