//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosWeb.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gestores_Bd
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<int> lanzamiento { get; set; }
        public string desarrollador { get; set; }
    }
}
